name: VARIABLE LEARNING
on: 
    workflow_dispatch:
    # schedule:
    #     - cron: "*/1 * * * *"
    push:

env: 
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          timeout-minutes: 1
          run: echo docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

        - name: Docker login
          run: echo docker login -username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: docker
        concurrency: 
          cancel-in-progress: true
          group: production-deployment
        runs-on: ubuntu-latest
        steps:
         - name: Docker Run
           run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest